spring.profiles.active: production

---

spring:
  profiles: production

---

spring:
  profiles: development
hibernate:
  show_sql: true
  hbm2ddl:
    auto: create
    import_files: "/scripts/test_data.sql"
spring.jpa.properties.javax.persistence.schema-generation:
  create-source: metadata
  scripts:
    action: create
    create-target: "target/create_schema.sql"
logging.level:
  org.hibernate.tool: DEBUG
