spring.profiles.active: production

---

spring:
  profiles: production

---

spring:
  profiles: development
  jpa:
    generate-ddl: true
    show-sql: true

    properties.javax.persistence.schema-generation:
      create-source: metadata
      hibernate:
        ddl-auto: create
#        hbm2ddl.import_files: "scripts/test_data.sql"
      scripts:
        create-target: "target/create_schema.sql"
  datasource:
    data: classpath:/scripts/test_data.sql
#hibernate:
#  show_sql: true
#  hbm2ddl:
#    auto: create
#    import_files: "/scripts/test_data.sql"
logging.level:
  org.hibernate.tool: DEBUG
