insert into product (name, increment, unit ) values ('картошка', 2, 'кг');
insert into product (name, increment, unit ) values ('морковка', 1, 'кг');
insert into product (name, increment, unit ) values ('репчатый лук', 1, 'кг');
insert into product (name, increment, unit ) values ('льняное масло', 1, 'бут');
insert into product (name, increment, unit ) values ('хлеб', 1, 'ед');
insert into product (name, increment, unit ) values ('рыба', 1, 'кг');
insert into product (name, increment, unit ) values ('молоко', 8, 'л');
insert into product (name, increment, unit ) values ('яйца', 30, 'шт');
insert into product (name, increment, unit ) values ('кофе', 200, 'гр');
insert into product (name, increment, unit ) values ('куриное филе', 3, 'кг');
insert into product (name, increment, unit ) values ('куриные голени', 2, 'кг');
insert into product (name, increment, unit ) values ('сок', 4, 'л');
insert into product (name, increment, unit ) values ('укроп', 400, 'гр');
insert into product (name, increment, unit ) values ('зеленый лук', 400, 'гр');
insert into product (name, increment, unit ) values ('яблоки', 2, 'кг');
insert into product (name, increment, unit ) values ('сыр', 700, 'гр');
insert into product (name, increment, unit ) values ('пельмени', 1000, 'гр');
insert into product (name, increment, unit ) values ('мороженое', 400, 'гр');
insert into product (name, increment, unit ) values ('сливочное масло', 200, 'гр');
insert into product (name, increment, unit ) values ('гречка', 450, 'гр');
insert into product (name, increment, unit ) values ('красный рис', 450, 'гр');
insert into product (name, increment, unit ) values ('чипсы', 1, 'уп');
insert into product (name, increment, unit ) values ('конфеты', 200, 'гр');
insert into product (name, increment, unit ) values ('шоколад', 2, 'пл');
insert into product (name, increment, unit ) values ('мешки для мусора', 1, 'уп');
insert into product (name, increment, unit ) values ('салфетки', 1, 'уп');
insert into product (name, increment, unit ) values ('мыло', 1, 'уп');
insert into product (name, increment, unit ) values ('шампунь', 1, 'бут');
insert into product (name, increment, unit ) values ('шампунь 3 в 1', 1, 'бут');
insert into product (name, increment, unit ) values ('стиральный порошок', 9, 'кг');
insert into product (name, increment, unit ) values ('зубная паста', 1, 'тюбик');
insert into product (name, increment, unit ) values ('одноразовые контейнеры', 1, 'уп');
insert into product (name, increment, unit ) values ('одноразовые вилки', 1, 'уп');
insert into product (name, increment, unit ) values ('капуста', 2, 'кг');
insert into product (name, increment, unit ) values ('помидоры', 2.5, 'кг');
insert into product (name, increment, unit ) values ('грибы', 500, 'гр');
insert into product (name, increment, unit ) values ('овсянка', 1, 'уп');
insert into product (name, increment, unit ) values ('туалетная бумага', 12, 'рул');
insert into product (name, increment, unit ) values ('губки', 10, 'шт');
insert into product (name, increment, unit ) values ('средство для мытья посуды', 1, 'л');
insert into product (name, increment, unit ) values ('подсолнечное масло', 900, 'мл');
insert into product (name, increment, unit ) values ('арахис', 2, 'кг');
insert into product (name, increment, unit ) values ('чай', 100, 'пак');
insert into product (name, increment, unit ) values ('пакеты', 1, 'шт');
insert into product (name, increment, unit ) values ('соль', 1, 'кг');
insert into product (name, increment, unit ) values ('сахар', 1, 'кг');
insert into product (name, increment, unit ) values ('творог 0.5%', 2000, 'гр');
insert into product (name, increment, unit ) values ('перец черный', 1, 'уп');
insert into product (name, increment, unit ) values ('перец красный', 1, 'уп');
insert into product (name, increment, unit ) values ('пемолюкс', 1, 'бут');
insert into product (name, increment, unit ) values ('доместос', 1, 'бут');
insert into product (name, increment, unit ) values ('манная крупа', 1, 'уп');
insert into product (name, increment, unit ) values ('кока кола зеро', 5, 'бут');
insert into product (name, increment, unit ) values ('индейка', 300, 'гр');
insert into product (name, increment, unit ) values ('свекла', 0.4, 'кг');
insert into product (name, increment, unit ) values ('перец красный сладкий', 0.25, 'кг');
insert into product (name, increment, unit ) values ('куркума', 1, 'уп');
insert into product (name, increment, unit ) values ('хмели-сунели', 1, 'уп');
insert into product (name, increment, unit ) values ('корица', 1, 'уп');
insert into product (name, increment, unit ) values ('творог 9%', 400, 'гр');
insert into product (name, increment, unit ) values ('очищенные семечки подсолнечные', 1200, 'гр');
insert into product (name, increment, unit ) values ('майонез 67%', 400, 'гр');
insert into product (name, increment, unit ) values ('скумбрия', 700, 'гр');
insert into product (name, increment, unit ) values ('сардины', 700, 'гр');
insert into product (name, increment, unit ) values ('бананы', 1, 'кг');
insert into product (name, increment, unit ) values ('шпинат', 400, 'гр');
insert into product (name, increment, unit ) values ('порошок для посудомоечной машины', 3, 'кг');
insert into product (name, increment, unit ) values ('кокосовое масло', 450, 'гр');
insert into product (name, increment, unit ) values ('клубника', 200, 'гр');
insert into product (name, increment, unit ) values ('куриный фарш', 800, 'гр');
insert into product (name, increment, unit ) values ('сметана', 500, 'гр');
insert into product (name, increment, unit ) values ('соль с калием', 700, 'гр');
insert into product (name, increment, unit ) values ('арахисовая паста', 510, 'гр');
insert into product (name, increment, unit ) values ('детская зубная паста', 1, 'шт');
insert into product (name, increment, unit ) values ('пирожное медвежонок', 1, 'шт');
insert into product (name, increment, unit ) values ('голубика', 125, 'гр');
insert into product (name, increment, unit ) values ('сыр голландский', 500, 'гр');
insert into product (name, increment, unit ) values ('томаты черри', 250, 'гр');
insert into product (name, increment, unit ) values ('блины', 500, 'гр');
insert into product (name, increment, unit ) values ('мандарины', 0.5, 'кг');
insert into product (name, increment, unit ) values ('гуруши', 0.5, 'кг');
insert into product (name, increment, unit ) values ('говядина', 0.5, 'кг');
insert into product (name, increment, unit ) values ('мука', 2, 'кг');
insert into product (name, increment, unit ) values ('яблочный уксус', 250, 'мл');
insert into product (name, increment, unit ) values ('тортик', 1, 'шт');
insert into product (name, increment, unit ) values ('мед', 250, 'гр');
insert into product (name, increment, unit ) values ('черный чай', 25, 'пак');
